# Generic, formatter-friendly config.
select = ["B", "D3", "E", "F", "C901"]

# Never enforce `E501` (line length violations). This should be handled by formatters.
ignore = ["E501"]

[mccabe]
max-complexity = 10
