name: Test python

on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - pyproject.toml
      - dbt_artifacts_parser/**/*.py
      - tests/**/*.py
      - pylintrc
  push:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For repo checkout
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    env:
      PYTHON_PACKAGE_NAME: YOUR_PYTHON_PACKAGE_NAME
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          bash dev/setup.sh --deps "development"
      - name: Run tests
        run: |
          uv run bash dev/test_python.sh
      - name: Test build
        run: |
          uv run bash dev/build.sh
      # - name: Test installation
      #   run: |
      #     pip install -e .
      #     python -c 'import ${{ env.PYTHON_PACKAGE_NAME }}'
